apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: graphhire
  labels:
    app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: job_matching_backend-api:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info"]
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
