"""Initial schema

Revision ID: 02aff5b5466f
Revises: None
Create Date: 2026-05-22 05:31:08.405307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02aff5b5466f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('graph_node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_vi', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('graph_node_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=True),
    sa.Column('learnability_tier', sa.String(length=10), nullable=False),
    sa.Column('learnability_weight', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('parent_skill_id', sa.Integer(), nullable=True),
    sa.Column('esco_uri', sa.String(length=500), nullable=True),
    sa.Column('onet_code', sa.String(length=50), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('graph_node_id', sa.Integer(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('current_salary_vnd', sa.BigInteger(), nullable=True),
    sa.Column('expected_salary_min_vnd', sa.BigInteger(), nullable=True),
    sa.Column('expected_salary_max_vnd', sa.BigInteger(), nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_job_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_text_vi', sa.Text(), nullable=True),
    sa.Column('raw_text_en', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('faiss_index_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('apply_url', sa.String(length=1000), nullable=False),
    sa.Column('title_vi', sa.Text(), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('company_name_vi', sa.Text(), nullable=True),
    sa.Column('company_name_en', sa.Text(), nullable=True),
    sa.Column('job_address', sa.String(length=255), nullable=True),
    sa.Column('job_address_detail', sa.Text(), nullable=True),
    sa.Column('job_requirements_vi', sa.Text(), nullable=True),
    sa.Column('job_requirements_en', sa.Text(), nullable=True),
    sa.Column('job_description_vi', sa.Text(), nullable=True),
    sa.Column('job_description_en', sa.Text(), nullable=True),
    sa.Column('benefit_vi', sa.Text(), nullable=True),
    sa.Column('benefit_en', sa.Text(), nullable=True),
    sa.Column('salary_raw', sa.String(length=255), nullable=True),
    sa.Column('salary_min_vnd', sa.BigInteger(), nullable=True),
    sa.Column('salary_max_vnd', sa.BigInteger(), nullable=True),
    sa.Column('salary_min_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('salary_max_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('salary_is_negotiable', sa.Boolean(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('experience_raw', sa.String(length=100), nullable=True),
    sa.Column('experience_min_years', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('experience_max_years', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('job_category', sa.String(length=100), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('faiss_index_id', sa.Integer(), nullable=True),
    sa.Column('graph_node_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_apply_url'), 'jobs', ['apply_url'], unique=False)
    op.create_index(op.f('ix_jobs_experience_max_years'), 'jobs', ['experience_max_years'], unique=False)
    op.create_index(op.f('ix_jobs_experience_min_years'), 'jobs', ['experience_min_years'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_job_address'), 'jobs', ['job_address'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_salary_max_vnd'), 'jobs', ['salary_max_vnd'], unique=False)
    op.create_index(op.f('ix_jobs_salary_min_vnd'), 'jobs', ['salary_min_vnd'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('is_self_assessed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id', 'skill_id', name='idx_cv_skills_unique')
    )
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hgat_score', sa.DECIMAL(precision=7, scale=6), nullable=True),
    sa.Column('skill_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('experience_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('salary_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('location_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('overall_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('slwg_total_penalty', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('skill_gap_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id', 'job_id', name='idx_cv_job_match_unique')
    )
    op.create_table('job_similarity',
    sa.Column('job_id_a', sa.Integer(), nullable=False),
    sa.Column('job_id_b', sa.Integer(), nullable=False),
    sa.Column('jaccard_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['job_id_a'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id_b'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id_a', 'job_id_b')
    )
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('importance_rank', sa.Integer(), nullable=True),
    sa.Column('extracted_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='idx_job_skills_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    op.drop_table('job_similarity')
    op.drop_table('job_matches')
    op.drop_table('cv_skills')
    op.drop_table('apply_clicks')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_jobs_salary_min_vnd'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_salary_max_vnd'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_address'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_experience_min_years'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_experience_max_years'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_apply_url'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('cvs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('locations')
    op.drop_table('companies')
    # ### end Alembic commands ###
