"""add cv_type column

Revision ID: 880f75eefcf5
Revises: e3942a8c1dc6
Create Date: 2026-05-27 01:09:37.544268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880f75eefcf5'
down_revision: Union[str, None] = 'e3942a8c1dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('cv_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'cv_type')
    # ### end Alembic commands ###
